# Continuous integration and delivery of the main branch.

name: CI/CD
on:
  push:
    branches:
    - main

jobs:
  # Release on Github and Docker
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout github repo
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Write commit message
      run: git log --format=%B -n 1 ${{ github.event.after }} > release_notes.txt

    - name: Github Bumpversion Action
      id: version-bump
      uses: jasonamyers/github-bumpversion-action@v1.0.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: "patch"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tags: true

    - name: Create Github release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version-bump.outputs.new_ver }}
        release_name: 'v${{ steps.version-bump.outputs.new_ver }}'
        body_path: "release_notes.txt"
        draft: false
        prerelease: false

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Build Docker images
      run: |-
        gcloud config set account aou-lr-docker-builder@broad-dsp-lrma.iam.gserviceaccount.com
        gcloud auth configure-docker -q us-central1-docker.pkg.dev
        ./scripts/build_docker_images.sh ${{ steps.version-bump.outputs.new_ver }}

