# Continuous integration test of any branch.

name: CI
on:
  push:
    branches-ignore:
    - main2

jobs:
  # Run Python tests on Github runner
  tox_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        $CONDA/bin/conda install -y -c bioconda womtool 
        $CONDA/bin/conda config --add channels conda-forge
        $CONDA/bin/conda install -y -c conda-forge miniwdl shellcheck
        echo "$CONDA/bin" >> $GITHUB_PATH

    - name: Test with tox
      run: tox

  # Build Docker image
  build_docker:
    runs-on: ubuntu-latest

    steps:
    - name: Work around permissions issue
      run: git config --global --add safe.directory /__w/longbow/longbow
    - uses: 'actions/checkout@v2'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Image
      run: |-
        TAG=$(git rev-parse --abbrev-ref HEAD)
        cd docker
        docker build --build-arg branch=$TAG -t us.gcr.io/broad-dsp-lrma/lr-longbow:$TAG .
        gcloud auth configure-docker -q
        docker push -q us.gcr.io/broad-dsp-lrma/lr-longbow:$TAG
